print(323 + 543)
print(8687 - 424)
print(54 * 23)
print(54535 / 2342)
print(2423 // 432)
print("luka miqeladze")
print("hello world")
print("goa")
print("lego")
print("chad")
print("book")
print("food")
print("water")
print("no coke")
print("programing")
print("freinds")
print("soccer")
print("football")
print("boy")
print("girl")
print("abs")
print("arm")
print("math")
print("school")
print("teacher")
print("mouse")
print("key")
print("home")
print("speed")
print("fast")
print("healthy")
print("true")
print("no games")
print("blue")
print("red")
print("green")
print("heart")
print("love")
print("sister")
print("brother")