a = input("enter nummber")
b = input("enter nummber")
print(a + b)
a = input("enter nummber")
b = input("enter nummber")
print(a + b)
a = input("enter nummber")
b = input("enter nummber")
print(a + b)