x = input('enter x :')
y = input('enter y :')
print(int(x) + int(y))
a = input ('enter x :')
b = input ('enter y :')
print(int(a)+ int(b))
m = input ('enter m :')
r  = input ('enter r :')
print(int(m) + int(r))
j = input ('enter j :')
t  = input ('enter t :')
print(int(j) + int(t))
f = input('enter f :')
v = input('enter v :')
print(int(f) + int(v))
d = input ('enter d :')
p = input ('enter p :')
print(int(d)+ int(p))
g = input ('enter g :')
o  = input ('enter o :')
print(int(g) + int(o))
w = input ('enter w :')
q  = input ('enter q :') 
print(int(w) + int(q))
x = input('enter x :')
y = input('enter y :')
print(int(x) + int(y))
a = input ('enter x :')
b = input ('enter y :')
print(int(a) + int(b))

m = input ('enter m :')
r  = input ('enter r :')
print(int(m) - int(r))
j = input ('enter j :')
t  = input ('enter t :')
print(int(j) - int(t))
f = input('enter f :')
v = input('enter v :')
print(int(f) - int(v))
d = input ('enter d :')
p = input ('enter p :')
print(int(d)- int(p))
g = input ('enter g :')
o  = input ('enter o :')
print(int(g) - int(o))
w = input ('enter w :')
q  = input ('enter q :') 
print(int(w) - int(q))
x = input('enter x :')
y = input('enter y :')
print(int(x) - int(y))
a = input ('enter x :')
b = input ('enter y :')
print(int(a)- int(b))
m = input ('enter m :')
r  = input ('enter r :')
print(int(m) - int(r))
j = input ('enter j :')
t  = input ('enter t :')
print(int(j) - int(t))

f = input('enter f :')
v = input('enter v :')
print(int(f) * int(v))
d = input ('enter d :')
p = input ('enter p :')
print(int(d)* int(p))
g = input ('enter g :')
o  = input ('enter o :')
print(int(g) * int(o))
w = input ('enter w :')
q  = input ('enter q :') 
print(int(w) * int(q))
x = input('enter x :')
y = input('enter y :')
print(int(x) * int(y))
a = input ('enter x :')
b = input ('enter y :')
print(int(a)* int(b))
m = input ('enter m :')
r  = input ('enter r :')
print(int(m) * int(r))
j = input ('enter j :')
t  = input ('enter t :')
print(int(j) * int(t))
f = input('enter f :')
v = input('enter v :')
print(int(f) * int(v))

d = input ('enter d :')
p = input ('enter p :')
print(int(d)// int(p))
g = input ('enter g :')
o  = input ('enter o :')
print(int(g) // int(o))
w = input ('enter w :')
q  = input ('enter q :') 
print(int(w) // int(q))
x = input('enter x :')
y = input('enter y :')
print(int(x) // int(y))
a = input ('enter x :')
b = input ('enter y :')
print(int(a)// int(b))
m = input ('enter m :')
r  = input ('enter r :')
print(int(m) // int(r))
j = input ('enter j :')
t  = input ('enter t :')
print(int(j) // int(t))
f = input('enter f :')
v = input('enter v :')
print(int(f) // int(v))
d = input ('enter d :')
p = input ('enter p :')
print(int(d)// int(p))
g = input ('enter g :')
o  = input ('enter o :')
print(int(g) // int(o))

w = input ('enter w :')
q  = input ('enter q :') 
print(int(w) / int(q))
e = input ('enter e :')
h  = input ('enter h :') 
print(int(e) / int(h))
x = input('enter x :')
y = input('enter y :')
print(int(x) / int(y))
a = input ('enter x :')
b = input ('enter y :')
print(int(a)/ int(b))
m = input ('enter m :')
r  = input ('enter r :')
print(int(m) / int(r))
j = input ('enter j :')
t  = input ('enter t :')
print(int(j) / int(t))
f = input('enter f :')
v = input('enter v :')
print(int(f) / int(v))
d = input ('enter d :')
p = input ('enter p :')
print(int(d) / int(p))
g = input ('enter g :')
o  = input ('enter o :')
print(int(g) / int(o))
w = input ('enter w :')
q  = input ('enter q :') 
print(int(w) / int(q))
x = input ('enter x')
y = input('enter y')
print(int(x) / int(y))